import os
from travelperk_http_python.builder.builder import build
from utils import write_output
travelperk = build(os.environ["SANDBOX_API_KEY"], True)
invoice = travelperk.expenses().invoices().get("CR-01-2")
write_output("invoice", [
    invoice.serial_number,
    invoice.profile_id,
    invoice.profile_name,
    invoice.billing_information.legal_name,
    invoice.billing_information.vat_number,
    invoice.billing_information.address_line_1,
    invoice.billing_information.address_line_2,
    invoice.billing_information.city,
    invoice.billing_information.postal_code,
    invoice.billing_information.country_name,
    invoice.mode,
    invoice.status,
    invoice.issuing_date,
    invoice.billing_period,
    invoice.from_date,
    invoice.to_date,
    invoice.due_date,
    invoice.currency,
    invoice.total,
    invoice.taxes_summary,
    invoice.reference,
    invoice.travelperk_bank_account.bank_name,
    invoice.travelperk_bank_account.account_number,
    invoice.travelperk_bank_account.bic,
    invoice.travelperk_bank_account.reference,
    invoice.pdf[0:40],  # This link will change every time
    invoice.lines.total,
    invoice.lines.data,
    invoice.lines.data[0].expense_date,
    invoice.lines.data[0].description,
    invoice.lines.data[0].quantity,
    invoice.lines.data[0].unit_price,
    invoice.lines.data[0].non_taxable_unit_price,
    invoice.lines.data[0].tax_percentage,
    invoice.lines.data[0].tax_amount,
    invoice.lines.data[0].tax_regime,
    invoice.lines.data[0].total_amount,
    invoice.lines.data[0].metadata.trip_id,
    invoice.lines.data[0].metadata.trip_name,
    invoice.lines.data[0].metadata.service,
    invoice.lines.data[0].metadata.travelers,
    invoice.lines.data[0].metadata.travelers[0].name,
    invoice.lines.data[0].metadata.travelers[0].email,
    invoice.lines.data[0].metadata.travelers[0].external_id,
    invoice.lines.data[0].metadata.start_date,
    invoice.lines.data[0].metadata.end_date,
    invoice.lines.data[0].metadata.cost_center,
    invoice.lines.data[0].metadata.labels,
    invoice.lines.data[0].metadata.labels[0],
    invoice.lines.data[0].metadata.vendor.code,
    invoice.lines.data[0].metadata.vendor.name,
    invoice.lines.data[0].metadata.out_of_policy,
    invoice.lines.data[0].metadata.approvers,
    invoice.lines.data[0].metadata.booker.name,
    invoice.lines.data[0].metadata.booker.email,
    invoice.lines.data[0].metadata.booker.external_id,
])
