import os
from travelperk_http_python.builder.builder import build
from utils import write_output
travelperk = build(os.environ["SANDBOX_API_KEY"], True)
lines = travelperk.expenses().invoices().lines_query().set_offset(1).set_limit(10).get()
write_output("invoice_lines", [
    lines.total,
    lines.offset,
    lines.limit,
    lines.invoice_lines,
    lines.invoice_lines[0].expense_date,
    lines.invoice_lines[0].description,
    lines.invoice_lines[0].quantity,
    lines.invoice_lines[0].unit_price,
    lines.invoice_lines[0].non_taxable_unit_price,
    lines.invoice_lines[0].tax_percentage,
    lines.invoice_lines[0].tax_amount,
    lines.invoice_lines[0].tax_regime,
    lines.invoice_lines[0].total_amount,
    lines.invoice_lines[0].metadata.trip_id,
    lines.invoice_lines[0].metadata.trip_name,
    lines.invoice_lines[0].metadata.service,
    lines.invoice_lines[0].metadata.travelers,
    lines.invoice_lines[0].metadata.travelers[0].name,
    lines.invoice_lines[0].metadata.travelers[0].email,
    lines.invoice_lines[0].metadata.travelers[0].external_id,
    lines.invoice_lines[0].metadata.start_date,
    lines.invoice_lines[0].metadata.end_date,
    lines.invoice_lines[0].metadata.cost_center,
    lines.invoice_lines[0].metadata.labels,
    lines.invoice_lines[0].metadata.labels[0],
    lines.invoice_lines[0].metadata.vendor.code,
    lines.invoice_lines[0].metadata.vendor.name,
    lines.invoice_lines[0].metadata.out_of_policy,
    lines.invoice_lines[0].metadata.approvers,
    lines.invoice_lines[0].metadata.booker.name,
    lines.invoice_lines[0].metadata.booker.email,
    lines.invoice_lines[0].metadata.booker.external_id,
    lines.invoice_lines[0].invoice_serial_number,
    lines.invoice_lines[0].profile_id,
    lines.invoice_lines[0].profile_name,
    lines.invoice_lines[0].invoice_mode,
    lines.invoice_lines[0].invoice_status,
    lines.invoice_lines[0].issuing_date,
    lines.invoice_lines[0].due_date,
    lines.invoice_lines[0].currency,
])
