version: '3'
services:

  python-probe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-probe
    tty: false
    working_dir: /app
    environment:
      API_KEY: ${API_KEY}
      SANDBOX_API_KEY: ${SANDBOX_API_KEY}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URL: ${REDIRECT_URL}
      ACCESS_TOKEN_PATH: ${ACCESS_TOKEN_PATH}
    volumes:
      - ./:/app
      - ./output:/app/output
    ports:
      - "4444:4444"
    command: ["/bin/sh","run"]
