version: '3'
services:

  python-probe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-probe
    tty: false
    working_dir: /app
    environment:
      API_KEY: ${API_KEY}
    volumes:
      - ./:/app
      - ./output:/app/output
    ports:
      - "4444:4444"
    command: ["/bin/sh","run"]
