#!/bin/bash
echo "Get travel restrictions"
pipenv run python ./scripts/get_travel_restrictions.py
echo "Get local summary"
pipenv run python ./scripts/get_local_summary.py
echo "Get safety measures"
pipenv run python ./scripts/get_safety_measures.py
echo "List cost centers"
pipenv run python ./scripts/cost_centers.py
echo "Get cost center"
pipenv run python ./scripts/cost_center.py
echo "List users"
pipenv run python ./scripts/users.py
echo "List trips"
pipenv run python ./scripts/list_trips.py
echo "List bookings"
pipenv run python ./scripts/list_bookings.py
echo "List webhooks"
pipenv run python ./scripts/webhooks.py
echo "Get webhook"
pipenv run python ./scripts/webhook.py
echo "Test webhook"
pipenv run python ./scripts/test_webhook.py
echo "Service provider config"
pipenv run python ./scripts/service_provider_config.py
echo "List resource types"
pipenv run python ./scripts/list_resource_types.py
echo "List all schemas"
pipenv run python ./scripts/schemas.py
echo "User schema details"
pipenv run python ./scripts/user_schema.py
echo "Enterprise user schema details"
pipenv run python ./scripts/enterprise_schema.py
echo "List users (scim)"
pipenv run python ./scripts/list_scim.py
echo "Get user"
pipenv run python ./scripts/get_user.py
echo "List invoice profiles"
pipenv run python ./scripts/list_invoice_profiles.py
echo "List invoices"
pipenv run python ./scripts/list_invoices.py
echo "Get invoice"
pipenv run python ./scripts/get_invoice.py
echo "Get invoice PDF"
pipenv run python ./scripts/get_invoice_pdf.py
echo "List invoice lines"
pipenv run python ./scripts/invoice_lines.py
echo "List billing periods"
pipenv run python ./scripts/billing_periods.py
echo "List statuses"
pipenv run python ./scripts/statuses.py
echo "List sorting values"
pipenv run python ./scripts/sorting_values.py
echo "List genders"
pipenv run python ./scripts/genders.py
echo "List languages"
pipenv run python ./scripts/languages.py
echo "List location types"
pipenv run python ./scripts/location_types.py
echo "Create user"
pipenv run python ./scripts/create_user.py
echo "Replace user"
pipenv run python ./scripts/replace_user.py
echo "Delete user"
pipenv run python ./scripts/delete_user.py
echo "Create webhook"
pipenv run python ./scripts/create_webhook.py
echo "Update webhook"
pipenv run python ./scripts/update_webhook.py
echo "Delete webhook"
pipenv run python ./scripts/delete_webhook.py
echo "Update cost center"
pipenv run python ./scripts/update_cost_center.py
echo "Bulk update cost centers"
pipenv run python ./scripts/bulk_update_cost_centers.py
