version: '3'
services:

  php-probe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-probe
    tty: false
    working_dir: /usr/src/app
    environment:
      API_KEY: ${API_KEY}
      SANDBOX_API_KEY: ${SANDBOX_API_KEY}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URL: ${REDIRECT_URL}
      ACCESS_TOKEN_PATH: ${ACCESS_TOKEN_PATH}
    volumes:
      - ./:/usr/src/app
      - vendor:/usr/src/app/vendor
      - ./output:/usr/src/app/output
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    command: ["/bin/sh","run"]

volumes:
  vendor:
